---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role
  namespace: dev
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "list", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developers
  namespace: dev
subjects:
- kind: User
  name: devone@kenthua.joonix.net
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
