apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /helloweb
        backend:
          serviceName: helloweb-backend
          servicePort: 8080
