kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: hello
spec:
    hosts:
        - "hello.app"
    pathPrefixes:
        - /
    scaleTargetRef:
        name: hello
        kind: Deployment
        apiVersion: apps/v1
        service: hello
        port: 8080
    replicas:
        min: 0
        max: 2
    scaledownPeriod: 300
    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 100
            window: 1m
