apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/kenthua-testing/main-service
    context: mainservice
  - image: gcr.io/kenthua-testing/service1
    context: service1
deploy:
  kubectl:
    manifests:
    - mainservice/kubernetes/deployment.yaml
    - service1/kubernetes/deployment.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild:
      projectId: kenthua-testing
