- op: add
  path: /spec/template/spec/containers/0/env/0
  value:
    name: GOOGLE_APPLICATION_CREDENTIALS
    value: /var/secrets/google/secret.json
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    name: google-cloud-key
    mountPath: /var/secrets/google
- op: add
  path: /spec/template/spec/volumes/0
  value:
    name: google-cloud-key
    secret:
      secretName: istio-mixer-key
- op: replace
  path: /spec/template/spec/containers/0/args/1
  value: --field=1
