apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- output.yaml

patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: example
    namespace: default
    version: v1
