apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: gemma-3-4b-it-hf
spec:
  modelName: google/gemma-3-4b-it
  criticality: Critical
  poolRef:
    name: vllm-gemma-3-4b

