apiVersion: v1
kind: Service
metadata:
  name: mainservice
  labels:
    app: mainservice
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: mainservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainservice
  template:
    metadata:
      labels:
        app: mainservice
    spec:
      containers:
      - name: mainservice
        image: gcr.io/kenthua-testing/main-service
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE1_URL
          value: "http://service1.default:8080"
        ports:
        - containerPort: 8080
---
