apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service1-entry
spec:
  hosts:
  - service1.test-service2.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8080
    protocol: http
  resolution: DNS
  addresses:
  - 127.255.0.20
  endpoints:
  - address: 35.202.15.223
    ports:
      http1: 15443
