apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: whereami
spec:
  selector:
    matchLabels:
      app: whereami
  endpoints:
  - port: 8080
    path: /metrics
    interval: 30s
