apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: whereami
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       whereami
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: "whereami"
        minAllowed:
          cpu: "100m"
        controlledResources: ["cpu"]
        controlledValues: "RequestsAndLimits"