apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources
namespace: kenthua-test-standalone
patchesJSON6902:
- target:
    group: container.cnrm.cloud.google.com
    version: v1beta1
    kind: ContainerCluster
    name: cc-test-k8s
  patch: |-
    - op: replace
      path: /spec/workloadIdentityConfig/identityNamespace
      value: kenthua-test-standalone.svc.id.goog