kind: HealthCheckPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: health-check-policy
  namespace: default
spec:
  targetRef:
    group: ""
    kind: Service
    name: vllm-gemma-3-1b
  default:
    config:
      type: HTTP
      httpHealthCheck:
          requestPath: /health
          port: 8000
