apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: node-web
  name: node-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: node-web
  type: LoadBalancer
status:
  loadBalancer: {}
