kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager-role
  namespace: team1
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - deployments
  - serviceaccounts
  - events
  verbs:
  - get
  - list
  - create
  - delete
