kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager
  namespace: team1
subjects:
  - kind: Group
    name: team1@kenthua.joonix.net
roleRef:
  kind: Role
  name: resource-manager-role
  apiGroup: rbac.authorization.k8s.io
