apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echoserver
        image: nicksardo/echoserver:latest
        imagePullPolicy: Always
        ports:
        - name: echo-443
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: my-echo
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"https-port":"HTTPS"}'   # Must map port-name to HTTPS for the GCP ingress controller
  labels:
    app: echo
spec:
  type: NodePort
  ports:
  - port: 12345  # Port doesn't matter as nodeport is used for Ingress
    targetPort: echo-443
    protocol: TCP
    name: https-port
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-echo-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"  
  labels:
    app: echo
spec:
  tls:
    - secretName: gcp-tls
  defaultBackend:
    service:
      name: my-echo
      port:
        name: https-port