apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - image: gcr.io/kenthua-testing/python-mysql
        name: mysql
        env:
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: MYSQL_DB_NAME
          value: test
        - name: MYSQL_HOSTNAME
          value: "127.0.0.1"
        - name: MYSQL_HOST_PORT
          value: "3306"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=kenthua-testing:us-central1:sql-test=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    run: mysql
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    name: app-port
  selector:
    run: mysql
